disabled_rules:
  - trailing_whitespace
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - vertical_whitespace

excluded:
  - Pods
  - Carthage
  - .build
  - DerivedData

force_cast: error
force_try: error
line_length:
  warning: 120
  error: 200
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - x
    - y
    - vm
